#!/bin/bash
# CopyFiles2 - Script #2 to copy configuration files to their proper location.
#		(First save originals as *.orig)

# Samba configuration
mv /etc/samba/smb.conf /etc/samba/smb.conf.orig
cp /root/FS1/config/smb.conf /etc/samba/

# DNS name resolving
cp /root/FS1/config/resolv.conf /etc/resolv.conf

# WSD Daemon
cp /root/FS1/config/wsdd /usr/bin/
cp /root/FS1/config/wsdd.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable wsdd.service
systemctl start wsdd.service

# Authentication
mv /etc/nsswitch.conf /etc/nsswitch.conf.orig
cp /root/FS1/config/nsswitch.conf /etc/

# sudo for Domain Admins
cp /root/FS1/config/SAMDOM /etc/sudoers.d/
