#!/bin/bash
# CopyFiles2 - Script #2 to copy configuration files to their proper location.
#		(Fist save originals as *.orig)

# Copy script to cron.hourly that sets RFC2307 attributes in the SAMBA AD DC
cp /root/DC1/RFC2307 /etc/cron.hourly/
/etc/cron.hourly/RFC2307
chown 10500 -R /var/lib/samba/sysvol/samdom.example.com/Policies/*

# DNS name resolving
cp /root/DC1/config/resolv.conf2 /etc/resolv.conf

# NTP Time Service
mv /etc/ntp.conf /etc/ntp.conf.orig
cp /root/DC1/config/ntp.conf /etc/
systemctl restart ntp.service

# WSD Daemon
cp /root/DC1/config/wsdd /usr/bin/
cp /root/DC1/config/wsdd.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable wsdd.service
systemctl start wsdd.service

# Authentication
mv /etc/nsswitch.conf /etc/nsswitch.conf.orig
cp /root/DC1/config/nsswitch.conf /etc/

# sudo for Domain Admins
cp /root/DC1/config/SAMDOM /etc/sudoers.d/

# DHCP Service
cp /root/DC1/config/isc-dhcp-server /etc/default/
cp /root/DC1/etc/config/dhcpd.conf /etc/dhcp/

