#!/bin/bash
# CopyFiles - Script to copy configuration files to their proper location.
#		(Fist save originals as *.orig)

# Static IP
mv /etc/network/interfaces /etc/network/interfaces.orig
cp /root/DC1/config/interfaces /etc/network/

# DNS name resolving
mv /etc/resolv.conf /etc/resolv.conf.orig
cp /root/DC1/config/resolv.conf /etc/

# Local host name
mv /etc/hosts /etc/hosts.orig
cp /root/DC1/config/hosts /etc/

# Default UMASK
mv /etc/login.defs /etc/login.defs.orig
cp /root/DC1/config/login.defs /etc/

# WSD Daemon
cp /root/DC1/config/wsdd /usr/bin/
cp /root/DC1/config/wsdd.service /etc/systemd/system/

# Authentication
mv /etc/nsswitch.conf /etc/nsswitch.conf.orig
cp /root/DC1/config/nsswitch.conf /etc/

# sudo for Domain Admins
cp /root/DC1/config/SAMDOM /etc/sudoers.d/

# DHCP Service
cp /root/DC1/config/isc-dhcp-server /etc/default/
cp /root/DC1/etc/config/dhcpd.conf /etc/dhcp/

