#!/bin/bash
# CopyFiles1 - Script #1 to copy configuration files to their proper location.
#		(Fist save originals as *.orig)

# Static IP
mv /etc/network/interfaces /etc/network/interfaces.orig
cp /root/DC2/config/interfaces /etc/network/

# Local host name
mv /etc/hosts /etc/hosts.orig
cp /root/DC2/config/hosts /etc/

# Default UMASK
mv /etc/login.defs /etc/login.defs.orig
cp /root/DC2/config/login.defs /etc/

