#!/bin/bash
# RFC2307 - Script to set RFC2307 attributes in the SAMBA Active Directory Domain Controller
 
FIRST_ID=10000
 
# Find users and computers without a uidNumber and groups without a gidNumber
 
# Add a uidNumber, home directory and shell to non-system user accounts (RID >= 1000)
while read DN; do
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	if [ $RID -ge 1000 ]
	then
		printf "Adding a uidNumber to '$DN'\n"
		IDNUMBER=$(($FIRST_ID + $RID))
 
		TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
		printf "dn: $DN\n" >$TMP_FILE
		printf "changeType: modify\n" >>$TMP_FILE
		printf "add: uidNumber\n" >>$TMP_FILE
		printf "uidNumber: ${IDNUMBER}\n" >>$TMP_FILE
		printf "add: unixHomeDirectory\n" >>$TMP_FILE
		printf "unixHomeDirectory: /home/%%U\n" >>$TMP_FILE
		printf "add: loginShell\n" >>$TMP_FILE
		printf "loginShell: /bin/bash\n" >>$TMP_FILE
 
		ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
		cat $TMP_FILE
	else
		printf "Skipping system user '$DN'\n"
	fi
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=User)(!(ObjectClass=computer))(!(uidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
# Add a uidNumber to computers
while read DN; do
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	if [ $RID -ge 1000 ]
	then
		printf "Adding a uidNumber to '$DN'\n"
		IDNUMBER=$(($FIRST_ID + $RID))
 
		TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
		printf "dn: $DN\n" >$TMP_FILE
		printf "changeType: modify\n" >>$TMP_FILE
		printf "add: uidNumber\n" >>$TMP_FILE
		printf "uidNumber: ${IDNUMBER}\n" >>$TMP_FILE
 
		ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
		cat $TMP_FILE
	else
		printf "Skipping computer '$DN'\n"
	fi
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=User)(ObjectClass=computer)(!(uidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
# Add a gidNumber to all groups
while read DN; do
	printf "Adding a gidNumber to '$DN'\n"
	RID=$(ldbsearch -H /var/lib/samba/private/sam.ldb -s base -b "$DN" objectSid | grep objectSid | awk -F "-" '{print $NF}')
	IDNUMBER=$(($FIRST_ID + $RID))
 
	TMP_FILE=$(mktemp "/tmp/$(basename $0)-XXXXX")
	printf "dn: $DN\n" >$TMP_FILE
	printf "changeType: modify\n" >>$TMP_FILE
	printf "add: gidNumber\n" >>$TMP_FILE
	printf "gidNumber: ${IDNUMBER}\n" >>$TMP_FILE
 
	ldbmodify -H /var/lib/samba/private/sam.ldb $TMP_FILE
	cat $TMP_FILE
done < <(ldbsearch -H /var/lib/samba/private/sam.ldb '(&(ObjectClass=Group)(!(gidNumber=*)))' dn | grep "dn:" | awk -F ':' '{print $2}')
 
# Cleanup temp files
rm /tmp/$0-*
